import ResponsiveAppBar from '@/components/Navbar'
import { Toolbar, CssBaseline } from '@mui/material'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import CustomTheme from '@/components/Theme'
import './globals.css'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <CssBaseline/>
        <ResponsiveAppBar/>
        <Toolbar/>
        <CustomTheme>
          {children}
        </CustomTheme>
        </body>
    </html>
  )
}
